version: '3'
services:
  http:
    container_name: reconciliation-system_http
    build: .
    command: go run cmd/http_server/main.go
    ports: 
      - 8080:8080
    restart: on-failure
    env_file:
      - .env 
    volumes:
      - .:/reconciliation-system
    depends_on:
      - db

  cron:
    container_name: reconciliation-system_cron
    build: .
    command: go run cmd/cron_server/main.go
    restart: on-failure
    env_file:
      - .env 
    volumes:
      - .:/reconciliation-system
    depends_on:
      - db
       
  db:
    image: postgres
    container_name: reconciliation-system_db
    environment:
      - POSTGRES_USER=${DB_USER} 
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data

volumes:
  database_postgres:


